package Green.Bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import Green.Bean.FileResult;

import Green.Bean.FileResultDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileResultDaoConfig;

    private final FileResultDao fileResultDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileResultDaoConfig = daoConfigMap.get(FileResultDao.class).clone();
        fileResultDaoConfig.initIdentityScope(type);

        fileResultDao = new FileResultDao(fileResultDaoConfig, this);

        registerDao(FileResult.class, fileResultDao);
    }
    
    public void clear() {
        fileResultDaoConfig.clearIdentityScope();
    }

    public FileResultDao getFileResultDao() {
        return fileResultDao;
    }

}
