package Green.Bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FILE_RESULT".
*/
public class FileResultDao extends AbstractDao<FileResult, Long> {

    public static final String TABLENAME = "FILE_RESULT";

    /**
     * Properties of entity FileResult.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Downpath = new Property(1, String.class, "downpath", false, "DOWNPATH");
        public final static Property Threadid = new Property(2, Integer.class, "threadid", false, "THREADID");
        public final static Property Downlength = new Property(3, Integer.class, "downlength", false, "DOWNLENGTH");
    }


    public FileResultDao(DaoConfig config) {
        super(config);
    }
    
    public FileResultDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FILE_RESULT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DOWNPATH\" TEXT," + // 1: downpath
                "\"THREADID\" INTEGER," + // 2: threadid
                "\"DOWNLENGTH\" INTEGER);"); // 3: downlength
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FILE_RESULT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FileResult entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String downpath = entity.getDownpath();
        if (downpath != null) {
            stmt.bindString(2, downpath);
        }
 
        Integer threadid = entity.getThreadid();
        if (threadid != null) {
            stmt.bindLong(3, threadid);
        }
 
        Integer downlength = entity.getDownlength();
        if (downlength != null) {
            stmt.bindLong(4, downlength);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FileResult entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String downpath = entity.getDownpath();
        if (downpath != null) {
            stmt.bindString(2, downpath);
        }
 
        Integer threadid = entity.getThreadid();
        if (threadid != null) {
            stmt.bindLong(3, threadid);
        }
 
        Integer downlength = entity.getDownlength();
        if (downlength != null) {
            stmt.bindLong(4, downlength);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FileResult readEntity(Cursor cursor, int offset) {
        FileResult entity = new FileResult( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // downpath
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // threadid
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // downlength
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FileResult entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDownpath(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setThreadid(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setDownlength(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FileResult entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FileResult entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FileResult entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
